#import <React/RCTBridgeModule.h>
@interface RCT_EXTERN_MODULE(FounderRouteAnalyticsModule, NSObject)
RCT_EXTERN_METHOD(configure:(NSString *)key endpoint:(NSString *)endpoint appId:(NSString *)appId properties:(NSArray *)properties traits:(NSArray *)traits verificationId:(NSString *)verificationId collectionMode:(NSString *)collectionMode propertyId:(NSString *)propertyId environment:(NSString *)environment)
RCT_EXTERN_METHOD(optOut)
RCT_EXTERN_METHOD(optIn)
RCT_EXTERN_METHOD(destroy)
RCT_EXTERN_METHOD(setCollectionMode:(NSString *)mode)
RCT_EXTERN_METHOD(setConsent:(BOOL)value)
RCT_EXTERN_METHOD(identify:(NSString *)identifier token:(NSString *)token traits:(NSDictionary *)traits)
RCT_EXTERN_METHOD(setAccount:(NSString *)identifier)
RCT_EXTERN_METHOD(track:(NSString *)name properties:(NSDictionary *)properties outcomeId:(NSString *)outcomeId)
RCT_EXTERN_METHOD(screen:(NSString *)name)
RCT_EXTERN_METHOD(setCampaignContext:(NSString *)url)
RCT_EXTERN_METHOD(reset)
RCT_EXTERN_METHOD(flush)
RCT_EXTERN_METHOD(getDiagnostics:(RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
@end
